<h1>Vos postes</h1>
<table>
    <thead>
        <tr>
            <th>Titre</th>
            <th>Contenu</th>
        </tr>
    </thead>
    <tbody>
        <?php
            // echo "<pre>";
            // print_r($_SESSION['user']);
            // echo "</pre>";
            foreach($_SESSION['user']->getPosts() as $post)
            {
                echo
                "<tr>
                    <td>".$post->getTitle()."</td>
                    <td>".$post->getContent()."</td>
                </tr>";
            }
        ?>
    </tbody>
</table>
<?php
    require "_post-create.phtml";
    require "_post-edit.phtml";
?>