<main>
    <h1>Accueil</h1>
    <h3>Categories</h3>
    <ul>
        <?php
            foreach($_SESSION['categories'] as $category)
            {
                echo "<li>".$category['name']."</li>";
            }
        ?>
    </ul>
    <h3>Posts</h3>
    <ul>
        <?php
            foreach($_SESSION['posts'] as $post)
            {
                echo "<li>".$post['title']."</li>";
            }
        ?>
    </ul>
</main>