<h1>Vos catégories</h1>
<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($categories as $category)
            {
                echo
                "<tr>
                    <td>".$category['name']."</td>
                    <td>".$category['description']."</td>
                </tr>";
            }
        ?>
    </tbody>
</table>
<?php
    require "_post-category-create.phtml";
    require "_post-category-edit.phtml";
?>