<form action="index.php" method="POST">
    <fieldset>
        <label for="login">Login</label>
        <input type="email" name="login" id="login"/>
    </fieldset>
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit-login" id="submit-login"/>
    </fieldset>
    <input type="hidden" name="formName" id="formName"/>
</form>